name: Development Bot

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: .
    - name: Set up Node.js
      uses: actions/setup-node@@v4
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Create emptyconfig.json 
      run: echo '{}' > config.json

    - name: Register commands to Beta
      run: node ./deploy-commands-actions.js
      env:
        BM64_BETA_CLIENTID: ${{ secrets.BM64_BETA_CLIENTID }}
        BM64_BETA_TOKEN: ${{ secrets.BM64_BETA_TOKEN }}
